{
    'name': 'Sales Representative Portal & Route Management',
    'version': '19.0.2.4.0',
    'summary': 'Field sales portal for Odoo 19: routes, GPS visits, orders, collections, cheques, returns, expenses, targets and offline sync - on standard Odoo documents',
    'description': """
Sales Representative Portal & Route Management
==============================================
Portal interface + Route/Visit management + integration layer over standard Odoo
(sale.order, account.move, account.payment, stock.picking).
""",
    'category': 'Sales',
    'author': 'Eng. M.Aboelmagde',
    'website': 'https://www.youtube.com/@odoolab',
    'license': 'OPL-1',
    'price': 299.0,
    'currency': 'USD',
    'images': [
        'static/description/banner.png',
        'static/description/screenshots/19_portal_desktop.png',
        'static/description/screenshots/20_portal_dashboard_phone.png',
        'static/description/screenshots/01_home.png',
        'static/description/screenshots/07_quick_actions.png',
        'static/description/screenshots/08_customer_360.png',
        'static/description/screenshots/10_visit.png',
        'static/description/screenshots/02_route.png',
        'static/description/screenshots/04_new_order.png',
        'static/description/screenshots/11_receipt.png',
        'static/description/screenshots/14_cheques.png',
        'static/description/screenshots/15_return.png',
        'static/description/screenshots/09_targets.png',
        'static/description/screenshots/13_expenses.png',
        'static/description/screenshots/12_outstanding.png',
        'static/description/screenshots/16_followups.png',
        'static/description/screenshots/17_offline.png',
        'static/description/screenshots/18_manager_dashboard.png',
        'static/description/screenshots/06_home_arabic.png',
    ],
    'depends': ['base', 'mail', 'portal', 'hr', 'sales_team', 'sale_management', 'sale_stock', 'account', 'stock'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'data/data.xml',
        'data/alerts.xml',
        'views/backend_views.xml',
        'views/backend_views_v2.xml',
        'views/backend_views_v3.xml',
        'views/report_receipt.xml',
        'views/inherit_views.xml',
        'views/employee_views.xml',
        'views/menus.xml',
        'views/portal_templates.xml',
        'views/portal_templates_v2.xml',
        'views/portal_templates_v3.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'mo_sales_rep_portal/static/src/dashboard/dashboard.js',
            'mo_sales_rep_portal/static/src/dashboard/dashboard.xml',
            'mo_sales_rep_portal/static/src/dashboard/dashboard.scss',
        ],
    },
    'installable': True,
    'application': True,
}
