from . import insurance_company
from . import insurance_plan
from . import insurance_coverage_rule
from . import insurance_policy
from . import res_partner
from . import res_company
from . import res_config_settings
from . import sale_order
from . import insurance_authorization
from . import insurance_claim
from . import account_move
from . import insurance_dashboard
