{
    'name': 'Pre-Production Management',
    'version': '18.0.1.4.1',
    'category': 'Manufacturing',
    'author': 'Eng. M.Aboelmagde',
    'maintainer': 'Eng. M.Aboelmagde',
    'website': 'https://www.youtube.com/@odoolab',
    'images': ['static/description/banner.png', 'static/description/offer.png', 'static/description/workflow.png',
               'static/description/kanban.png', 'static/description/form.png', 'static/description/quality.png',
               'static/description/dashboard.png', 'static/description/report.png', 'static/description/settings.png'],
    'price': 149.00,
    'currency': 'USD',
    'summary': 'Sales Order -> Material/Packaging Issue -> Quality Approvals -> Manufacturing Order',
    'depends': ['sale_management', 'stock', 'mrp'],
    'data': [
        'security/pp_security.xml',
        'security/ir.model.access.csv',
        'data/pp_data.xml',
        'views/pp_order_views.xml',
        'views/pp_config_views.xml',
        'views/inherit_views.xml',
        'views/pp_dashboard.xml',
        'views/pp_menus.xml',
        'report/pp_report.xml',
    ],
    'assets': {'web.assets_backend': ['pre_production/static/src/dashboard/*', 'pre_production/static/src/scss/*.scss']},
    'application': True,
    'license': 'LGPL-3',
}
