{
    'name': 'Partner Reference Sequence',
    'version': '19.0.2.0.0',
    'summary': 'Auto-generate reference codes for customers, suppliers and contacts',
    'category': 'Contacts',
    'author': 'Eng. M.Aboelmagde',
    'website': 'https://www.youtube.com/@odoolab',
    'license': 'OPL-1',
    'price': 19.00,
    'currency': 'USD',
    'support': 'odoolabtech.offical',
    'images': ['static/description/banner.png', 'static/description/how_it_works.png', 'static/description/setup_steps.png'],
    'depends': ['base'],
    'data': [
        'data/sequence_data.xml',
        'views/res_partner_views.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
    'post_init_hook': '_create_company_sequences',
}
